### ISSUE TITLE
Unknown command line flag

### ISSUE THREAD

**Issue by Lay4U** [greydanus/crypto-rnn#3]
Traceback (most recent call last):
  File "C:/Users/ML/Downloads/crypto-rnn-master/main.py", line 82, in <module>
    FLAGS.meta_dir = 'meta/' + FLAGS.cipher + '/' # directory to save loss history, figures, etc.
  File "C:\Users\ML\Anaconda3\envs\me\lib\site-packages\tensorflow\python\platform\flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "C:\Users\ML\Anaconda3\envs\me\lib\site-packages\absl\flags\_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "C:\Users\ML\Anaconda3\envs\me\lib\site-packages\absl\flags\_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'meta_dir'

how can i solve it?

**Comment by vigorem** [comment]
For this very specific error, I solved it by declaring the two missing flags (past it after line 28):

    tf.app.flags.DEFINE_string("meta_dir", "", 'META_DIR')
    tf.app.flags.DEFINE_string("save_dir", "", 'META_DIR')

This does the trick
